# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "ngpixel"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    reviewers:
      - "ngpixel"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "rjsparks"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "ngpixel"
    groups:
      yarn:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/playwright"
    schedule:
      interval: "weekly"
    reviewers:
      - "ngpixel"
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/dev/coverage-action"
    schedule:
      interval: "weekly"
    reviewers:
      - "ngpixel"
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/dev/deploy-to-container"
    schedule:
      interval: "weekly"
    reviewers:
      - "ngpixel"
    groups:
      npm:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/dev/diff"
    schedule:
      interval: "weekly"
    reviewers:
      - "ngpixel"
    groups:
      npm:
        patterns:
          - "*"
