apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memcached.fullname" . }}
  labels:
    {{- include "datatracker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "datatracker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "datatracker.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "datatracker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-memcached
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ default "memcached" .Values.memcached.image.repository }}:{{ required "Must specify memcached tag" .Values.memcached.image.tag }}"
          imagePullPolicy: {{ default "IfNotPresent" .Values.memcached.image.imagePullPolicy }}
          env:
            {{- if .Values.memcached.env }}
            {{- toYaml .Values.memcached.env | nindent 12 }}
            {{- end }}
    {{- with .Values.memcached.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
    {{- end }}
          ports:
            - name: memcached
              containerPort: 11211
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.memcached.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.memcached.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.memcached.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.memcached.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: app-configmap
      {{- with .Values.memcached.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.memcached.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.memcached.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.memcached.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
    {{- end }}
