apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "datatracker-shared-volume-claim"
  labels:
    {{- include "datatracker.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.datatracker.name }}
spec:
  {{- with .Values.persistentVolumes.datatrackerSharedVolume }}
  storageClassName: {{ .storageClassName | quote }}
  {{- if .volumeName }}
  volumeName: {{ .volumeName | quote }}
  {{- end }}
  accessModes:
    {{- range  .accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .storage | quote }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "rabbitmq-data-claim"
  labels:
    {{- include "datatracker.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.rabbitmq.name }}
spec:
  {{- with .Values.persistentVolumes.rabbitmqDataVolume }}
  storageClassName: {{ .storageClassName | quote }}
  {{- if .volumeName }}
  volumeName: {{ .volumeName | quote }}
  {{- end }}
  accessModes:
    {{- range  .accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .storage | quote }}
  {{- end }}
