{{- if .Values.serviceAccounts.datatracker.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datatracker.serviceAccountName.datatracker" . }}
  labels:
    {{- include "datatracker.datatracker.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.datatracker.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}