{{- if .Values.serviceAccounts.memcached.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "datatracker.serviceAccountName.memcached" . }}
  labels:
    {{- include "datatracker.memcached.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.memcached.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}