# GITHUB ACTIONS - WORKFLOW

# Build the database dev docker image with the latest database dump every night
# so that developers don't have to manually build it themselves.

name: Nightly Dev DB Image

# Controls when the workflow will run
on:
  # Run every night
  schedule:
    - cron: '0 0 * * *'

  # Run on db.Dockerfile changes
  push:
    branches:
      - main
    paths:
      - 'docker/db.Dockerfile'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: datatracker-db

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
          
      - name: Get Current Date as Tag
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/db.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ietf-tools/datatracker-db:nightly-${{ steps.date.outputs.date }}
            ghcr.io/ietf-tools/datatracker-db:latest
